### ISSUE TITLE
Implement in the coder package?

### ISSUE THREAD

**Issue by eribul** [bjoroeKI/Charlson-comorbidity-index-revisited#1]
Hi there!

I just read your paper, which I liked very much!
I have a small R package `coder` where I have implemented some of the standard codes for CCI and ECI etc. 
It would be nice to implement your versions there as well :-)
Either I'll try to do it some time in the future (of course with proper references to your paper and repo), or if you would like to give it a try, I would be happy to inlude you as an athour of the package!

Package website: https://docs.ropensci.org/coder/

Related issue: https://github.com/ropensci/coder/issues/148

**Comment by bjoroeKI** [comment]
Thank you for the interest in our work. I will have a look at your package later this week.

**Comment by eribul** [comment]
som lite av en slump förresten så råkade rOpenSci publicera en blog post om det igår kväll :-)
https://ropensci.org/blog/2021/02/09/coder/
